server {
    listen 80;
    listen [::]:80;
    #listen 443 ssl;
    #listen [::]:443 ssl;
    server_name default_server;
    
    # Buffer size configuration
    client_max_body_size 300M;
    client_body_buffer_size 32k;
    client_header_buffer_size 8k;
    large_client_header_buffers 8 64k;
    
    # Root location for SPA
    gzip_types text/plain text/css application/json application/x-javascript
               text/xml application/xml application/xml+rss text/javascript;
    # Root location for SPA
    location / {
        root /usr/share/nginx/html/Parent-Management-System/browser;
        try_files $uri $uri/ /index.html;
        index index.html;
     }
    
    # API proxy configuration
    location /api {
        proxy_ssl_server_name on;
        rewrite /api/(.*) /$1 break;
        proxy_pass ${APP_API_URL};
    }
    
}
